### ISSUE TITLE
Unexpected token b in JSON at position 0

### ISSUE THREAD

**Issue by TexAgg** [khrome/where-parser#3]
I tried testing it with `var p = parser.parse("(a = b) or false");` and I got the error.
I noticed that it failed to parse the same input in issue #1 , but now it seems to fail on any input (I tried it with other [test cases](https://github.com/khrome/where-parser/blob/master/test.js#L13) and got similar errors).
Here is the entire error:
```
undefined:1
b
^

SyntaxError: Unexpected token b in JSON at position 0
    at Object.parse (native)
    at WhereParser.parse_discriminant (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:64:26)
    at mapFunction (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:30:35)
    at Array.map (native)
    at mapFunction (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:22:30)
    at Array.map (native)
    at WhereParser.parse_where (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:20:30)
    at WhereParser.parse (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:14:21)
    at Object.<anonymous> (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/server.js:9:16)
    at Module._compile (module.js:570:32)

```

and here is the rest of my code
```
const express = require('express');
const fs = require("fs");
const url = require('url');
const WhereParser = require('where-parser');

const app = express();
var parser = new WhereParser();

var p = parser.parse("(a = b) or false");
```

**Comment by khrome** [comment]
What happens when you run the tests? (run `mocha` in the project root)

**Comment by TexAgg** [comment]
```
  ․․․․

  0 passing (9ms)
  4 failing

  1) WhereParser parses a single level:
     SyntaxError: Unexpected token P in JSON at position 0
      at Object.parse (native)
      at WhereParser.parse_discriminant (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:64:26)
      at mapFunction (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:30:35)
      at Array.map (native)
      at WhereParser.parse_where (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:20:30)
      at WhereParser.parse (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:14:21)
      at Context.<anonymous> (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/test.js:13:29)
      at Test.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:196:15)
      at Runner.runTest (/usr/lib/nodejs/mocha/lib/runner.js:373:10)
      at /usr/lib/nodejs/mocha/lib/runner.js:451:12
      at next (/usr/lib/nodejs/mocha/lib/runner.js:298:14)
      at /usr/lib/nodejs/mocha/lib/runner.js:308:7
      at next (/usr/lib/nodejs/mocha/lib/runner.js:246:23)
      at Immediate.<anonymous> (/usr/lib/nodejs/mocha/lib/runner.js:275:5)
      at runCallback (timers.js:649:20)
      at tryOnImmediate (timers.js:622:5)
      at processImmediate [as _immediateCallback] (timers.js:594:5)

  2) WhereParser parses multiple levels:
     SyntaxError: Unexpected token s in JSON at position 0
      at Object.parse (native)
      at WhereParser.parse_discriminant (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:64:26)
      at mapFunction (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:30:35)
      at Array.map (native)
      at WhereParser.parse_where (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:20:30)
      at WhereParser.parse (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:14:21)
      at Context.<anonymous> (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/test.js:36:29)
      at Test.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:196:15)
      at Runner.runTest (/usr/lib/nodejs/mocha/lib/runner.js:373:10)
      at /usr/lib/nodejs/mocha/lib/runner.js:451:12
      at next (/usr/lib/nodejs/mocha/lib/runner.js:298:14)
      at /usr/lib/nodejs/mocha/lib/runner.js:308:7
      at next (/usr/lib/nodejs/mocha/lib/runner.js:246:23)
      at Immediate.<anonymous> (/usr/lib/nodejs/mocha/lib/runner.js:275:5)
      at runCallback (timers.js:649:20)
      at tryOnImmediate (timers.js:622:5)
      at processImmediate [as _immediateCallback] (timers.js:594:5)

  3) WhereParser parses an opening parenthetical:
     SyntaxError: Unexpected token b in JSON at position 0
      at Object.parse (native)
      at WhereParser.parse_discriminant (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:64:26)
      at mapFunction (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:30:35)
      at Array.map (native)
      at mapFunction (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:22:30)
      at Array.map (native)
      at WhereParser.parse_where (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:20:30)
      at WhereParser.parse (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:14:21)
      at Context.<anonymous> (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/test.js:67:29)
      at Test.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:196:15)
      at Runner.runTest (/usr/lib/nodejs/mocha/lib/runner.js:373:10)
      at /usr/lib/nodejs/mocha/lib/runner.js:451:12
      at next (/usr/lib/nodejs/mocha/lib/runner.js:298:14)
      at /usr/lib/nodejs/mocha/lib/runner.js:308:7
      at next (/usr/lib/nodejs/mocha/lib/runner.js:246:23)
      at Immediate.<anonymous> (/usr/lib/nodejs/mocha/lib/runner.js:275:5)
      at runCallback (timers.js:649:20)
      at tryOnImmediate (timers.js:622:5)
      at processImmediate [as _immediateCallback] (timers.js:594:5)

  4) WhereParser parses a 3 part boolean with internal parenthetical:
     SyntaxError: Unexpected end of JSON input
      at Object.parse (native)
      at WhereParser.parse_discriminant (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:64:26)
      at mapFunction (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:30:35)
      at Array.map (native)
      at WhereParser.parse_where (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:20:30)
      at WhereParser.parse (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/where-parser.js:14:21)
      at Context.<anonymous> (/home/matt/Dropbox/College/2016-2017/Spring/CSCE-315/hw2/whereServer/node_modules/where-parser/test.js:87:29)
      at Test.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:196:15)
      at Runner.runTest (/usr/lib/nodejs/mocha/lib/runner.js:373:10)
      at /usr/lib/nodejs/mocha/lib/runner.js:451:12
      at next (/usr/lib/nodejs/mocha/lib/runner.js:298:14)
      at /usr/lib/nodejs/mocha/lib/runner.js:308:7
      at next (/usr/lib/nodejs/mocha/lib/runner.js:246:23)
      at Immediate.<anonymous> (/usr/lib/nodejs/mocha/lib/runner.js:275:5)
      at runCallback (timers.js:649:20)
      at tryOnImmediate (timers.js:622:5)
      at processImmediate [as _immediateCallback] (timers.js:594:5)

```

**Comment by khrome** [comment]
After running the tests with a fresh checkout I also get the error you are getting... however the parent project's test suite all still passes: https://github.com/khrome/mangrove/blob/master/test.js#L7

I will not have time to investigate further until late next week.

In the interim I would welcome a patch that could both fix the failing tests and work in `mangrove`. If you aren't into that and are pressed for time, I recommend digging around inside `mangrove` to figure out why it is working when the main test suite in `where-parser` is not (a couple of well placed console.log()s will likely tell you).

Let me know how it goes!

**Comment by TexAgg** [comment]
Ok. I am actually pressed for time (I am trying to get a server up and
running by tonight) so I will look in mangrove and see if I can find out
what the problem is. Thank you
